cmake_minimum_required(VERSION 3.20)

# If building for Raspberry Pi Pico W, initialize Pico SDK before project()
if(PICO_BOARD)
    if(WIN32)
        set(USERHOME $ENV{USERPROFILE})
    else()
        set(USERHOME $ENV{HOME})
    endif()
    set(sdkVersion 2.3.1)
    set(toolchainVersion 15_2_Rel1)
    set(picotoolVersion 2.3.1)
    set(picoVscode ${USERHOME}/.pico-sdk/cmake/pico-vscode.cmake)
    if(EXISTS ${picoVscode})
        include(${picoVscode})
    endif()

    include(pico_w/pico_sdk_import.cmake)
    project(waiting_server_root C CXX ASM)
    pico_sdk_init()
    add_subdirectory(pico_w)
else()
    project(waiting_server_root CXX)
    message(STATUS "Configuring Linux target (pass -DPICO_BOARD=pico_w to build for Pico W)...")
    add_subdirectory(linux)
endif()
