#!/usr/bin/env python3
"""
tools/bake_config_packets.py

Generates shared/include/config_packets.hpp from captured Minecraft 26.3
configuration packets (protocol 777).
"""

import struct
import os

def decode_varint(data, offset):
    value = 0
    position = 0
    while True:
        b = data[offset]
        offset += 1
        value |= (b & 0x7F) << position
        if (b & 0x80) == 0:
            break
        position += 7
    return value, offset

def main():
    bin_path = 'old/scratch/captured_26_3_config_packets.bin'
    out_path = 'shared/include/config_packets.hpp'
    
    packets = []
    with open(bin_path, 'rb') as f:
        while True:
            hdr = f.read(8)
            if not hdr:
                break
            p_idx, p_len = struct.unpack('>II', hdr)
            p_data = f.read(p_len)
            packets.append(p_data)
            
    # Override packet 00 to brand "vanilla"
    # Length: 25 (0x19), Packet ID: 0x01, "minecraft:brand", "vanilla"
    pkt0_brand = (
        bytes([0x19, 0x01, 0x0F]) +
        b"minecraft:brand" +
        bytes([0x07]) +
        b"vanilla"
    )
    packets[0] = pkt0_brand
    
    lines = []
    lines.append("// Generated for Minecraft 26.3 (Protocol 777)")
    lines.append("// Auto-generated by tools/bake_config_packets.py")
    lines.append("#pragma once\n")
    lines.append("#include <cstdint>")
    lines.append("#include <cstddef>\n")
    lines.append("namespace waiting_server {\n")
    lines.append("struct PacketBlob {")
    lines.append("    const uint8_t* data;")
    lines.append("    size_t size;")
    lines.append("};\n")
    
    var_names = []
    for idx, p_data in enumerate(packets):
        var_name = f"config_packet_{idx:02d}"
        var_names.append(var_name)
        
        # Determine packet description
        off = 0
        pkt_len, off = decode_varint(p_data, off)
        pkt_id, off = decode_varint(p_data, off)
        desc = f"Packet ID 0x{pkt_id:02X}, size {len(p_data)} bytes"
        if pkt_id == 0x01:
            desc += " (Custom Payload: Brand)"
        elif pkt_id == 0x0D:
            desc += " (Update Enabled Features)"
        elif pkt_id == 0x0F:
            desc += " (Select Known Packs)"
        elif pkt_id == 0x07:
            reg_len, off = decode_varint(p_data, off)
            reg_name = p_data[off:off+reg_len].decode('utf-8')
            off += reg_len
            count, off = decode_varint(p_data, off)
            desc += f" (Registry: {reg_name}, {count} entries)"
        elif pkt_id == 0x0E:
            desc += " (Update Tags)"
        elif pkt_id == 0x03:
            desc += " (Finish Configuration)"
            
        lines.append(f"// {desc}")
        lines.append(f"alignas(4) inline constexpr uint8_t {var_name}[] = {{")
        
        # Format hex bytes in rows of 20
        chunk_lines = []
        for i in range(0, len(p_data), 20):
            chunk = p_data[i:i+20]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            if i + 20 < len(p_data):
                hex_str += ","
            chunk_lines.append(f"    {hex_str}")
        lines.extend(chunk_lines)
        lines.append("};\n")
        
    lines.append("inline constexpr PacketBlob CONFIG_PACKETS[] = {")
    for var in var_names:
        lines.append(f"    {{{var}, sizeof({var})}},")
    lines.append("};\n")
    lines.append("inline constexpr size_t NUM_CONFIG_PACKETS = sizeof(CONFIG_PACKETS) / sizeof(CONFIG_PACKETS[0]);\n")
    lines.append("} // namespace waiting_server\n")
    
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
        
    print(f"Generated {out_path} with {len(packets)} packets ({sum(len(p) for p in packets)} bytes total)")

if __name__ == '__main__':
    main()
