#!/usr/bin/env python3
"""
tools/bake_play_packets.py

Generates shared/include/play_packets.hpp from captured Minecraft 26.3
play packets (protocol 777).
"""

import struct
import re

def main():
    bin_path = 'old/scratch/captured_26_3_play_packets.bin'
    out_path = 'shared/include/play_packets.hpp'
    
    # Packet name map from GameProtocols
    with open('old/references/decomiled_26.3/net/minecraft/network/protocol/game/GameProtocols.java') as f:
        text = f.read()

    line252 = [line for line in text.splitlines() if 'CLIENTBOUND_TEMPLATE = ProtocolInfoBuilder.clientboundProtocol' in line][0]
    packet_names = re.findall(r'\.addPacket\((?:GamePacketTypes|CommonPacketTypes|CookiePacketTypes|PingPacketTypes)\.([A-Z0-9_]+)', line252)

    id_to_name = {0: 'CLIENTBOUND_BUNDLE_DELIMITER'}
    for idx, name in enumerate(packet_names, start=1):
        id_to_name[idx] = name

    packets = []
    with open(bin_path, 'rb') as f:
        while True:
            hdr = f.read(8)
            if not hdr:
                break
            pid, plen = struct.unpack('>II', hdr)
            pdata = f.read(plen)
            packets.append((pid, pdata))
            
    print(f"Read {len(packets)} packets from {bin_path}")
    
    # packets[0..27] are play_packet_000 to play_packet_027
    # packets[28] is Chunk Batch Finished (play_packet_037)
    
    lines = []
    lines.append("// Generated for Minecraft 26.3 (Protocol 777)")
    lines.append("// Auto-generated by tools/bake_play_packets.py from official 26.3 server capture")
    lines.append("#pragma once\n")
    lines.append("#include <cstdint>")
    lines.append("#include <cstddef>")
    lines.append('#include "config_packets.hpp"')
    lines.append('#include "lobby_chunks.hpp"\n')
    lines.append("namespace waiting_server {\n")
    
    for idx in range(28):
        pid, pdata = packets[idx]
        var_name = f"play_packet_{idx:03d}"
        pkt_name = id_to_name.get(pid, f"UNKNOWN_0x{pid:02X}")
        lines.append(f"// {var_name}: ID 0x{pid:02X} ({pkt_name}), size {len(pdata)} bytes")
        lines.append(f"alignas(4) inline constexpr uint8_t {var_name}[{len(pdata)}] = {{")
        chunk_lines = []
        for i in range(0, len(pdata), 16):
            chunk = pdata[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            if i + 16 < len(pdata):
                hex_str += ","
            chunk_lines.append(f"    {hex_str}")
        lines.extend(chunk_lines)
        lines.append("};\n")
        
    # Chunk Batch Finished
    pid_fin, pdata_fin = packets[28]
    pkt_name_fin = id_to_name.get(pid_fin, "CLIENTBOUND_CHUNK_BATCH_FINISHED")
    lines.append(f"// play_packet_037: ID 0x{pid_fin:02X} ({pkt_name_fin}), size {len(pdata_fin)} bytes")
    lines.append(f"alignas(4) inline constexpr uint8_t play_packet_037[{len(pdata_fin)}] = {{")
    chunk_lines = []
    for i in range(0, len(pdata_fin), 16):
        chunk = pdata_fin[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        if i + 16 < len(pdata_fin):
            hex_str += ","
        chunk_lines.append(f"    {hex_str}")
    lines.extend(chunk_lines)
    lines.append("};\n")
    
    lines.append("inline constexpr size_t NUM_PLAY_PACKETS = 54;\n")
    lines.append("inline constexpr PacketBlob PLAY_PACKETS[NUM_PLAY_PACKETS] = {")
    for idx in range(28):
        var_name = f"play_packet_{idx:03d}"
        pid, pdata = packets[idx]
        lines.append(f"    {{ {var_name}, {len(pdata)} }},")
    for i in range(25):
        lines.append(f"    LOBBY_CHUNKS[{i}],")
    lines.append(f"    {{ play_packet_037, {len(pdata_fin)} }},")
    lines.append("};\n")
    lines.append("} // namespace waiting_server\n")
    
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
        
    print(f"Generated {out_path} successfully!")

if __name__ == '__main__':
    main()
